### ISSUE TITLE
Debounce delay

### ISSUE THREAD

**Issue by chauser** [balthamos/steno-arduino#2]
Thanks for the code and the video. Going this route saved me hours over trying to debug the existing controller board that refused to talk to plover. I used a Teensy 2.0 for the controller and initially had lots of switch bounce -- multiple outputs for some switches of some strokes. I just increased  DEBOUNCE_PERIOD to 50 and it worked perfectly.

**Comment by balthamos** [comment]
Glad things worked for you!
